name: AndroidBuild
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"
          cache: "gradle"

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: QRCodeScanner.apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Build Release APK
        run: ./gradlew bundleRelease

      - name: Deploy to Play Store
        uses: wzieba/Distribution@v1
        with:
          serviceAccountEmail: ${{ secrets.PLAY_STORE_EMAIL }}
          serviceAccountJson: ${{ secrets.PLAY_STORE_JSON }}
          packageName: 'com.plcoding.qrcodescannercompose'
          track: 'internal'
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
